
name: sample-book-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Build started

  Deploy-dev:
    name: Deploy-DEV
    runs-on: ubuntu-latest
    needs: [build]  
    steps:      
      - name: Run a one-line script
        run: echo deploy to DEV srarted

  Tests-dev:
    name: Tests-DEV
    runs-on: ubuntu-latest
    needs: [Deploy-dev]  
    steps:      
      - name: Run a one-line script
        run: echo Test on DEV started

  Deploy-stg:
    name: Deploy-STG
    runs-on: ubuntu-latest
    needs: [Tests-dev]  
    steps:      
      - name: Run a one-line script
        run: echo deploy to STG srarted

  Tests-stg:
    name: Tests-STG
    runs-on: ubuntu-latest
    needs: [Deploy-stg]  
    steps:      
      - name: Run a one-line script
        run: echo Test on STG started
  Deploy-prd:
    name: Deploy-PRD
    runs-on: ubuntu-latest
    needs: [Tests-stg]  
    steps:      
      - name: Run a one-line script
        run: echo deploy to PRD srarted

  Tests-prd:
    name: Tests-PRD
    runs-on: ubuntu-latest
    needs: [Deploy-prd]  
    steps:      
      - name: Run a one-line script
        run: echo Test on PRD started